### ISSUE TITLE
Fix problem when connecting to Astra using Graal

### ISSUE THREAD

**Issue by tomekl007** [datastax/cassandra-quarkus#122]
When connecting to Astra using Graal the following error is propagated:
```

Caused by: java.security.KeyStoreException: JKS not found
	at java.security.KeyStore.getInstance(KeyStore.java:878)
	at com.datastax.oss.driver.internal.core.config.cloud.CloudConfigFactory.createKeyManagerFactory(CloudConfigFactory.java:209)
	at com.datastax.oss.driver.internal.core.config.cloud.CloudConfigFactory.createSslContext(CloudConfigFactory.java:198)
	at com.datastax.oss.driver.internal.core.config.cloud.CloudConfigFactory.createCloudConfig(CloudConfigFactory.java:130)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildDefaultSessionAsync(SessionBuilder.java:671)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildAsync(SessionBuilder.java:619)
	... 27 more
Caused by: java.security.NoSuchAlgorithmException: class configured for KeyStore (provider: SUN) cannot be found.
```
When the JKS is registered for reflection, it fails with:
```
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: JKS, provider: SUN, class: sun.security.provider.JavaKeyStore$DualFormatJKS)
	at java.security.Provider$Service.newInstance(Provider.java:1621)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.KeyStore.getInstance(KeyStore.java:848)
	... 32 more
Caused by: java.lang.NoSuchMethodException: sun.security.provider.JavaKeyStore$DualFormatJKS.<init>
	at java.lang.Class.getConstructor0(DynamicHub.java:3082)
	at java.lang.Class.getConstructor(DynamicHub.java:1825)
	at java.security.Provider$Service.newInstance(Provider.java:1594)
	... 36 more
```

**Comment by tomekl007** [comment]
It can be solved with:
```
quarkus.ssl.native=true
```
