### ISSUE TITLE
Quarkus ecosystem CI failing

### ISSUE THREAD

**Issue by gsmet** [datastax/cassandra-quarkus#136]
Hi,

I noticed the Cassandra ecosystem CI build failing (at least from time to time, I wasn't around for a week) with:
```
2020-09-29 05:33:12,090 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-3) HTTP Request to /rx/product failed, error id: a499b47f-0ae7-4f14-90df-bd7e3a774975-1: com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
	at com.datastax.oss.driver.api.core.DriverTimeoutException.copy(DriverTimeoutException.java:34)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
	at com.datastax.oss.quarkus.tests.dao.ProductReactiveDaoImpl__MapperGenerated.init(ProductReactiveDaoImpl__MapperGenerated.java:254)
	at com.datastax.oss.quarkus.tests.mapper.InventoryMapperImpl__MapperGenerated.lambda$productReactiveDao$1(InventoryMapperImpl__MapperGenerated.java:43)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.datastax.oss.quarkus.tests.mapper.InventoryMapperImpl__MapperGenerated.productReactiveDao(InventoryMapperImpl__MapperGenerated.java:43)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.datastax.oss.quarkus.tests.mapper.InventoryMapperProducer.produceProductReactiveDao(InventoryMapperProducer.java:51)
	at 
```

If it's just a timeout issue, could we make it larger? If it's not, any way the problem can be fixed?

Trying to get our CI all green.

Thanks!

**Comment by tomekl007** [comment]
Hello, it may be related to the fact that initializing daos is blocking.
We have WIP that make possibly fix this issue:
https://github.com/datastax/cassandra-quarkus/pull/127

**Comment by adutra** [comment]
It might be just a timeout issue after all. I will raise them to see if that solves the issue – it doesn't hurt to do so anyways.

**Comment by adutra** [comment]
Done in 31b3677, we'll see how it goes.
