### ISSUE TITLE
Quarkus + Cassandra

### ISSUE THREAD

**Issue by jaiprasad266** [datastax/cassandra-quarkus#210]
Hi ,
Trying to build an application where we fetch data from cassandra using the cassandra quarkus lib along with datastax drivers.

Followed the below doc on to build the sample quarkus cassandra application.
https://quarkus.io/guides/cassandra

Facing build errors , have included the errors.

dependency version used:

<cassandra-quarkus.version>1.1.2</cassandra-quarkus.version>
<driver.version>4.14.1</driver.version>

com.datastax.oss.quarkus cassandra-quarkus-client ${cassandra-quarkus.version}
<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-core</artifactId>
  <version>${driver.version}</version>
</dependency>

<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-query-builder</artifactId>
  <version>${driver.version}</version>
</dependency>

<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-mapper-runtime</artifactId>
  <version>${driver.version}</version>
</dependency>
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.main.FruitDao and qualifiers [@default]

* java member: org.acme.main.FruitService#dao
* declared on CLASS bean [types=[org.acme.main.FruitService, java.lang.Object], qualifiers=[@default, @Any], target=org.acme.main.FruitService]
at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:428)
at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:524)
at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:260)
... 13 more

I have the FruitDao class annotated with dao and the FruitMapper class with annotations Mapper and Daafactory just like the documentation .

Any inputs will be of help.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/QUAR-112) by [Unito](https://www.unito.io)

**Comment by jaiprasad266** [comment]
My pom was missing the cassandra-quarkus-mapper-processor plugin . Build is successful.
