### ISSUE TITLE
[JAVA-2776] Integration test failure for quarkus-ecosystem-ci, Quarkus master commit 72a6ff10cfe7b6fe7f8a6a68e0979f39f1b8288a

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#28]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2776">JAVA-2776</a>, originally reported by @absurdfarce on Thu, 14 May 2020 22:22:36 GMT.</p>
<hr />
<p>Noted on a local branch against master (commit 72a6ff10cfe7b6fe7f8a6a68e0979f39f1b8288a) with <span> <a href="https://datastax-oss.atlassian.net/browse/JAVA-2775" rel="nofollow">  JAVA-2775 </a> <span>Resolved</span> </span> already applied. The unit tests pass in this case but now we get the following IT failure:</p> 
<blockquote>
 <p>2020-05-14 16:44:50,778 INFO [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 30.517s. Listening on: <a href="http://0.0.0.0:8081/" rel="nofollow">http://0.0.0.0:8081</a> <br> 2020-05-14 16:44:50,779 INFO [io.quarkus] (main) Profile test activated. <br> 2020-05-14 16:44:50,779 INFO [io.quarkus] (main) Installed features: [cassandra-client, cdi, resteasy, smallrye-health] <br> [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 35.1 s &lt;&lt;&lt; FAILURE! - in com.datastax.oss.quarkus.CassandraHealthCheckIT <br> [ERROR] com.datastax.oss.quarkus.CassandraHealthCheckIT.healthCheckShouldReportStatusUp Time elapsed: 0.643 s &lt;&lt;&lt; ERROR! <br> java.lang.AbstractMethodError: io.restassured.internal.ResponseParserRegistrar.getProperty(Ljava/lang/String😉Ljava/lang/Object; <br> at com.datastax.oss.quarkus.CassandraHealthCheckIT.healthCheckShouldReportStatusUp(CassandraHealthCheckIT.java:36) </p> 
 <p>[INFO] Running com.datastax.oss.quarkus.ProductResourceIT <br> [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.02 s &lt;&lt;&lt; FAILURE! - in com.datastax.oss.quarkus.ProductResourceIT <br> [ERROR] com.datastax.oss.quarkus.ProductResourceIT.testSaveAndRetrieveProduct Time elapsed: 0.002 s &lt;&lt;&lt; ERROR! <br> java.lang.AbstractMethodError: io.restassured.internal.ResponseParserRegistrar.getProperty(Ljava/lang/String😉Ljava/lang/Object; <br> at com.datastax.oss.quarkus.ProductResourceIT.testSaveAndRetrieveProduct(ProductResourceIT.java:33) </p> 
 <p>[ERROR] com.datastax.oss.quarkus.ProductResourceIT.shouldSaveAndRetrieveUsingCustomNameConverterThatUsesReflection Time elapsed: 0.003 s &lt;&lt;&lt; ERROR! <br> java.lang.AbstractMethodError: io.restassured.internal.ResponseParserRegistrar.getProperty(Ljava/lang/String😉Ljava/lang/Object; <br> at com.datastax.oss.quarkus.ProductResourceIT.shouldSaveAndRetrieveUsingCustomNameConverterThatUsesReflection(ProductResourceIT.java:62) </p> 
 <p>2020-05-14 16:44:51,558 INFO [io.quarkus] (main) Quarkus stopped in 0.050s <br> [INFO] <br> [INFO] Results: <br> [INFO] <br> [ERROR] Errors: <br> [ERROR] CassandraHealthCheckIT.healthCheckShouldReportStatusUp:36 » AbstractMethod io....<br> [ERROR] ProductResourceIT.shouldSaveAndRetrieveUsingCustomNameConverterThatUsesReflection:62 » AbstractMethod<br> [ERROR] ProductResourceIT.testSaveAndRetrieveProduct:33 » AbstractMethod io.restassure...<br> [INFO]<br> [ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0</p>
</blockquote> 
<p>Looks to be a break in the linkage between REST-assured code and the Quarkus test framework</p>

**Comment by adutra** [comment]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2776?focusedCommentId=52590">JAVA-2776</a>, originally commented by @absurdfarce on Sat, 16 May 2020 04:22:50 GMT.</p>
<hr />
<p>This was kind of a strange one.</p> 
<p>Underlying error comes from <a href="https://github.com/rest-assured/rest-assured/blob/rest-assured-4.2.0/rest-assured/src/main/groovy/io/restassured/internal/ResponseParserRegistrar.groovy#L44" rel="nofollow">here</a> which represents an attempt to copy props from one Groovy object to another. The argument is of the same type as the class itself (they’re both ResponseParserRegistrar) yet the attempt to get the property from the arg fails because the arg doesn’t support the standard Groovy contract for getting and setting props. That’s quite odd since the class… is actually written in Groovy.</p> 
<p>Quarkus master does upgrade rest-assured from 4.2.0 (the version in 1.3.0) to 4.3.0, and that upgrade includes a major upgrade to Groovy 3 (see <a href="https://github.com/rest-assured/rest-assured/blob/master/changelog.txt#L7" rel="nofollow">the rest-assured changelog</a> for more on that). My best guess about the underlying cause here is that we’re mingling underlying versions, either rest-assured 4.2.0 with the new Groovy version or the inverse. If that’s the case the fixing the rest-assured version for integration tests at 4.2.0 (in effect removing uses of 4.3.0 for now) should solve the problem… and in my testing it appears to do just that.</p>
