### ISSUE TITLE
[JAVA-2719] Integrate with Netty event loop provided by Quarkus

### ISSUE THREAD

**Issue by adutra** [datastax/cassandra-quarkus#42]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2719">JAVA-2719</a>, originally reported by @tomekl007 on Thu, 2 Apr 2020 07:42:46 GMT.</p>
<hr />
<p>The quarkus framework is using one event loop that is reused for all extensions. They wrote:</p> 
<blockquote>
 <p>I am not familiar with the Cassandra driver, does it use Netty, some reactive library like vert.x? We do use netty and vert.x in Quarkus and we worked hard to use a single event loop. If we could align that would be awesome but could be a second step goal.</p>
</blockquote> 
<p>According to this discussion:</p> 
<p><a href="https://github.com/quarkusio/quarkus/issues/7876#issuecomment-603774204" rel="nofollow">https://github.com/quarkusio/quarkus/issues/7876#issuecomment-603774204</a> </p> 
<p>We could accept a Netty event-loop passing NettyOptions with event-loop that is provided by the quarkus into our extension.</p>

**Comment by adutra** [comment]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2719?focusedCommentId=52568">JAVA-2719</a>, originally commented by @tomekl007 on Tue, 12 May 2020 13:41:39 GMT.</p>
<hr />
<p>Current progress:</p> 
<p><a href="https://github.com/datastax/cassandra-quarkus/compare/master...java2719#diff-e217733643ccdd3fabe3a5d7c4911c41R124" rel="nofollow">https://github.com/datastax/cassandra-quarkus/compare/master...java2719#diff-e217733643ccdd3fabe3a5d7c4911c41R124</a></p> 
<p>Blocked on waiting for the release of fixes:</p> 
<ol> 
 <li>Injecting EventLoopGroup with proper proxy implementation:<br> <a href="https://github.com/quarkusio/quarkus/issues/7876#issuecomment-626797803" rel="nofollow">https://github.com/quarkusio/quarkus/issues/7876#issuecomment-626797803</a> </li> 
 <li>Fix of the cycle when injecting EventLoopGroup and health check:<br> <a href="https://github.com/quarkusio/quarkus/issues/7876#issuecomment-627260691" rel="nofollow">https://github.com/quarkusio/quarkus/issues/7876#issuecomment-627260691</a> </li> 
 <li>Closing EventLoopGroup by quarkus before the beans that are using it are released (waiting for a response):<br> <a href="https://github.com/quarkusio/quarkus/issues/7876#issuecomment-627170895" rel="nofollow">https://github.com/quarkusio/quarkus/issues/7876#issuecomment-627170895</a> </li> 
</ol>

**Comment by adutra** [comment]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2719?focusedCommentId=52572">JAVA-2719</a>, originally commented by @olim7t on Tue, 12 May 2020 17:35:30 GMT.</p>
<hr />
<p>A couple of preliminary comments:</p> 
<ul> 
 <li>mainEventLoop =&gt; driver ioEventLoop is obviously the right mapping.<br> However I'm not so sure about bossEventLoop =&gt; driver adminEventLoop. The "boss" event loop is used in a server to accept incoming client connections, and create child channels for conversing with them. Maybe it's not the right place to schedule our driver administrative tasks. We should at least figure out how Quarkus configures it (in particular how many threads). Using the main event loop for all driver tasks might be a more conservative approach.</li> 
 <li>which threads does "regular" Quarkus application code (e.g. REST endpoints) run on? Is it also mainEventLoop, or is there a dedicated thread pool for non-IO tasks? If it's mainEventLoop too, then all blocking driver operations (in particular synchronous Session.execute calls) must be avoided because they can deadlock. And to make it worse, the checks in <a href="https://github.com/datastax/java-driver/blob/4.x/core/src/main/java/com/datastax/oss/driver/internal/core/util/concurrent/BlockingOperation.java" rel="nofollow">BlockingOperation</a> don't work anymore since we're not creating the I/O threads.</li> 
</ul>

**Comment by adutra** [comment]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2719?focusedCommentId=52575">JAVA-2719</a>, originally commented by @tomekl007 on Wed, 13 May 2020 12:09:24 GMT.</p>
<hr />
<p>@olim7t Thank you for those points. </p> 
<p>I am doing an investigation, but also I asked the question on the quarkus ticket:<br> <a href="https://github.com/quarkusio/quarkus/issues/7876#issuecomment-627935101" rel="nofollow">https://github.com/quarkusio/quarkus/issues/7876#issuecomment-627935101</a></p> 
<p>The more I work on this ticket, the more I hesitate to share event loops between our driver and the quarkus. The reasons against it are:</p> 
<ul> 
 <li>we will not have influence (or have very limited) on the configuration of EventLoopGroups injected and used by the driver</li> 
 <li>Obviously, we need to get rid of our own configuration of netty event loop: <a href="https://github.com/datastax/java-driver/blob/258ec45593f3488bb5c256ecb3b9aa0d71355e65/core/src/main/java/com/datastax/oss/driver/internal/core/context/DefaultNettyOptions.java#L63-L75" rel="nofollow">https://github.com/datastax/java-driver/blob/258ec45593f3488bb5c256ecb3b9aa0d71355e65/core/src/main/java/com/datastax/oss/driver/internal/core/context/DefaultNettyOptions.java#L63-L75</a> It may be dangerous because those settings are optimized for our driver</li> 
 <li>Using provided event loops may yield a totally different performance of our driver. We would need to perform performance tests for every new release of quarkus (because they may introduce the performance regression) and on every release of our driver (I.e. last perf degradation of our driver because of the different netty version)</li> 
 <li>In the past, new releases of netty were a cause of performance drop of the driver. What if the quarkus will use an “incompatible” netty version? How to alleviate that problem?</li> 
</ul> 
<p>The pros of the sharing even loop is that the application will be less heavy: </p> 
<ul> 
 <li>fewer threads are needed for the final quarkus app</li> 
 <li>fewer context switches between quarkus HTTP event loop and our driver event loop</li> 
</ul> 
<p>Do you think that those pros are enough to implement this solution and pay the cost described in the section against it? Please let me know what do you think?</p> 
<p>There are other extensions, like for example amazon-dynamodb that are creating own netty event loop for processing without sharing it with the quarkus app (see for example io.quarkus.dynamodb.runtim.eNettyHttpClientConfig). So we will not be the first one if we will choose not to share.</p> 
<p><b>update:</b></p> 
<p>Regarding the configuration of even loops, it seems that it is using the io.quarkus.vertx.core.runtime.config.VertxConfiguration</p> 
<p>It is setting the workerPoolSize = 20 (<a href="https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/config/VertxConfiguration.java#L48-L49" rel="nofollow">https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/config/VertxConfiguration.java#L48-L49</a>) by default (<a href="https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java#L154-L162" rel="nofollow">https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java#L154-L162</a>), and eventLoopsPoolSize if not explicitly set then this logic is applied: <a href="https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java#L183-L194" rel="nofollow">https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java#L183-L194</a></p>

**Comment by adutra** [comment]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2719?focusedCommentId=52583">JAVA-2719</a>, originally commented by @absurdfarce on Thu, 14 May 2020 16:44:34 GMT.</p>
<hr />
<p>Seems to me like the lack of control over Netty versions (and possible future regressions in performance because of those changes) is the biggest issue there. I’m also imagining diagnosing <a href="https://datastax-oss.atlassian.net/browse/JAVA-2676" rel="nofollow">https://datastax-oss.atlassian.net/browse/JAVA-2676</a> on a platform where Netty is tightly integrated into multiple components so changing it for testing/validation purposes might be exceedingly complex.</p> 
<p>The benefits of sharing certainly aren’t nothing, but the more I think about it the more I share your skepticism @tomekl007 </p>

**Comment by adutra** [comment]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2719?focusedCommentId=52601">JAVA-2719</a>, originally commented by @olim7t on Mon, 18 May 2020 16:24:58 GMT.</p>
<hr />
<blockquote>
 <p>the more I think about it the more I share your skepticism</p>
</blockquote> 
<p>Same here. Keeping control over the Netty version is indeed a strong argument. If we keep our event loops separate, is our Netty version completely isolated from the one used by Quarkus core or other extensions?</p> 
<p>I'd also like to get to the bottom of this question from my other comment:</p> 
<blockquote>
 <p>which threads does "regular" Quarkus application code (e.g. REST endpoints) run on?</p>
</blockquote> 
<p>If synchronous execute calls are not possible, that's another very strong argument against.</p> 
<p>Lastly: is it conceivable to make this feature opt-in?</p>

**Comment by adutra** [comment]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2719?focusedCommentId=52602">JAVA-2719</a>, originally commented by @adutra on Mon, 18 May 2020 16:41:36 GMT.</p>
<hr />
<p>I think these concerns are worth a mailing list question. I’m pretty sure we’ll get detailed answers very quickly.</p> 
<blockquote>
 <p>is it conceivable to make this feature opt-in?</p>
</blockquote> 
<p>Was about to suggest the same, +1.</p>

**Comment by adutra** [comment]
<p>Imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2719?focusedCommentId=52648">JAVA-2719</a>, originally commented by @tomekl007 on Wed, 27 May 2020 11:00:41 GMT.</p>
<hr />
<p>I am debugging issue with:</p>  
<pre>2020-05-27 12:37:54,705 WARN  [io.net.uti.con.DefaultPromise] (vert.x-eventloop-thread-10) An exception was thrown by com.datastax.oss.driver.internal.core.pool.ChannelPool$SingleThreaded$$Lambda$2828/519790505.operationComplete(): java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at io.netty.util.concurrent.AbstractEventExecutor.submit(AbstractEventExecutor.java:115)
	at com.datastax.oss.driver.internal.core.pool.ChannelPool$SingleThreaded.lambda$onAllConnected$7(ChannelPool.java:370)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1158)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:760)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:736)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607)
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:762)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:524)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

</pre>  
<p>I found that the problem is in the ChannelPool.onAllConnected</p> 
<p>When adding logging:</p>  
<pre> channel
                .closeFuture()
                .addListener(
                    f -&gt; {
                      System.out.println(
                          "before submit().isTerminated " + adminExecutor.isTerminated());
                      System.out.println(
                          "before submit().isShutdown " + adminExecutor.isShutdown());
                      System.out.println(
                          "before submit().isShuttingDown " + adminExecutor.isShuttingDown());
                      adminExecutor
                          .submit(() -&gt; onChannelClosed(channel))
                          .addListener(UncaughtExceptions::log);
                    });</pre>  
<p>It shows that the adminExecutor injected by Quarkus is terminated. Because of this, the submit is failing.</p> 
<p>@olim7t is it possible that our action is executed some time after it should?<br> I mean that we are using addListener() method, so is it possible that our CqlSession is destroyed, quarkus detects that, the NettyEventLoop is closed, but the callback from addListener is still not executed, wdyt?</p>

**Comment by adutra** [comment]
<p>Pull request URL imported from <a href="https://datastax-oss.atlassian.net/browse/JAVA-2719">JAVA-2719</a>: <a href="https://github.com/datastax/cassandra-quarkus/pull/18">datastax/cassandra-quarkus/pull/18</a>.</p>
