### ISSUE TITLE
Timeout in Execution

### ISSUE THREAD

**Issue by UnvirtualHH** [datastax/cassandra-quarkus#99]
G'day, 

I'm using datastax graph exzessive in my application. I changed all code to use reactive programming with Mutiny and using alpha1 of cassandra-quarkus. 

A big problem is, that I often run in following exception:

`2020-06-24 11:00:27,059 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-5,5,main]=Thread[vert.x-eventloop-thread-5,5,main] has been blocked for 3341 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at java.base@13/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@13/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@13/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1867)
	at java.base@13/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137)
	at java.base@13/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1894)
	at java.base@13/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:143)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:612)
	at com.datastax.oss.quarkus.runtime.internal.quarkus.CassandraClientProducer.createCassandraClient(CassandraClientProducer.java:64)
	at com.datastax.oss.quarkus.runtime.internal.quarkus.CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_Bean.create(CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_Bean.zig:334)
	at com.datastax.oss.quarkus.runtime.internal.quarkus.CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_Bean.create(CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_Bean.zig:365)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:79)
	at io.quarkus.arc.impl.AbstractSharedContext$$Lambda$499/0x0000000800f30440.apply(Unknown Source)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction$$Lambda$503/0x0000000800f36440.get(Unknown Source)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at com.datastax.oss.quarkus.runtime.internal.quarkus.CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_ClientProxy.arc$delegate(CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_ClientProxy.zig:93)
	at com.datastax.oss.quarkus.runtime.internal.quarkus.CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_ClientProxy.execute(CassandraClientProducer_ProducerMethod_createCassandraClient_5a0b52609e90a9192707435ea76168cd66433ddc_ClientProxy.zig:282)
	at com.datastax.oss.quarkus.runtime.api.reactive.MutinyGraphReactiveSession.executeReactive(MutinyGraphReactiveSession.java:53)
	at de.grumbl.service.GrumblService.findAllNotBlockedMinified(GrumblService.java:230)
	at de.grumbl.service.GrumblService_ClientProxy.findAllNotBlockedMinified(GrumblService_ClientProxy.zig:571)
	at de.grumbl.controller.GrumblController.getAll(GrumblController.java:60)
	at de.grumbl.controller.GrumblController_RouteHandler_getAll_83d3b1a0d0ed0ce5d294317bafebefddea19561a.invoke(GrumblController_RouteHandler_getAll_83d3b1a0d0ed0ce5d294317bafebefddea19561a.zig:110)
	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:40)
	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:15)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:95)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$14.handle(VertxHttpRecorder.java:982)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$14.handle(VertxHttpRecorder.java:953)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup.handleHotReplacementRequest(VertxHttpHotReplacementSetup.java:39)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$$Lambda$97/0x0000000800caac40.handle(Unknown Source)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:108)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.access$100(HttpAuthorizer.java:26)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:125)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:114)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:68)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.operators.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
	at io.smallrye.mutiny.groups.UniCreate.lambda$item$2(UniCreate.java:205)
	at io.smallrye.mutiny.groups.UniCreate$$Lambda$754/0x00000008010f1040.accept(Unknown Source)
	at io.smallrye.mutiny.operators.UniCreateWithEmitter.subscribing(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$755/0x00000008010f1440.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:69)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:114)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.access$100(HttpAuthorizer.java:26)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:125)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:114)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:68)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.operators.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
	at io.smallrye.mutiny.groups.UniCreate.lambda$item$2(UniCreate.java:205)
	at io.smallrye.mutiny.groups.UniCreate$$Lambda$754/0x00000008010f1040.accept(Unknown Source)
	at io.smallrye.mutiny.operators.UniCreateWithEmitter.subscribing(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$755/0x00000008010f1440.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:69)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:114)
	at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.checkPermission(HttpAuthorizer.java:91)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:203)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$3.handle(HttpSecurityRecorder.java:195)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:140)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2$2.onItem(HttpSecurityRecorder.java:101)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.operators.UniCache.lambda$onItem$7(UniCache.java:117)
	at io.smallrye.mutiny.operators.UniCache$$Lambda$1002/0x0000000801217440.accept(Unknown Source)
	at java.base@13/java.util.ArrayList.forEach(ArrayList.java:1507)
	at io.smallrye.mutiny.operators.UniCache.onItem(UniCache.java:117)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.lambda$onItem$1(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1$$Lambda$780/0x000000080113a840.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$1.onItem(ContextPropagationUniInterceptor.java:35)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.onItem(UniSerializedSubscriber.java:72)
	at io.smallrye.mutiny.operators.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
	at io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator$1.accept(MpJwtValidator.java:54)
	at io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator$1.accept(MpJwtValidator.java:49)
	at io.smallrye.mutiny.operators.UniCreateWithEmitter.subscribing(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$755/0x00000008010f1440.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.operators.UniCache.lambda$subscribing$0(UniCache.java:37)
	at io.smallrye.mutiny.operators.UniCache$$Lambda$995/0x0000000801210040.run(Unknown Source)
	at io.smallrye.mutiny.operators.UniCache.subscribing(UniCache.java:65)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2$$Lambda$755/0x00000008010f1440.run(Unknown Source)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:217)
	at io.smallrye.context.SmallRyeThreadContext$$Lambda$573/0x0000000800febc40.execute(Unknown Source)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:51)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:43)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:38)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:49)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:101)
	at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:48)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:80)
	at io.quarkus.vertx.http.runtime.cors.CORSFilter.handle(CORSFilter.java:17)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:74)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:63)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
	at io.vertx.core.impl.ContextImpl$$Lambda$992/0x00000008011d3440.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$779/0x000000080113b440.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@13/java.lang.Thread.run(Thread.java:830)
`

My code looks like following:

Controller:

`@Route(path = "/all", methods = HttpMethod.GET, produces = MediaType.APPLICATION_JSON,
           consumes = MediaType.APPLICATION_JSON, order = 1)
    public void getAll(RoutingExchange ex) {
        service.findAll().subscribe()
                     .with(
                             item -> ex.response().end(item),
                             failure -> ex.response().end());
  }`

Service:

   ```
   private final QuarkusCqlSession session;

    @Inject
    public Service(QuarkusCqlSession quarkusCqlSession) {
        this.session = quarkusCqlSession;
    }

 
public Uni<String> findAll() {
        GraphTraversal<Vertex, Map<Object, Object>> gt = g.V().has("item", "blocked", false).elementMap("itemId", "x", "y", 
   "location", "topic");

        FluentGraphStatement statement = FluentGraphStatement.newInstance(gt).setGraphName("graphName");

        return session.executeReactive(statement).onItem().apply(reactiveGraphNode -> reactiveGraphNode.asMap()).onItem()
                      .apply(this::calculateSize).collectItems().asList().onItem().apply(this::convertListToJson);
    }
```

Maybe this is more related to quarkus/mutiny and I have to post it there, but maybe you see any error in using the quarkus-cassandra library.

**Comment by adutra** [comment]
That's interesting, the error is in `CassandraClientProducer#createCassandraClient`, this method is being executed on a Vertx event loop. We need to investigate if it's possible to return a `CompletionStage` here; or conversely, we need to execute that method outside of a Vertx event loop.

**Comment by UnvirtualHH** [comment]
One very interesting point, I mostly getting this exception when I run in a (unplanned) failure in one of my methods. But instead of a normal exception it is running into this blocked event loop.
